/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppToolbar: typeof import('./src/components/layout/AppToolbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ComponentPalette: typeof import('./src/components/layout/ComponentPalette.vue')['default']
    ControlLayout: typeof import('./src/components/layout/ControlLayout.vue')['default']
    copy: typeof import('./src/components/elements/ElButton copy.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Drawer: typeof import('primevue/drawer')['default']
    DrawerDialog: typeof import('./src/components/typeSelct/DrawerDialog.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    ElButton: typeof import('./src/components/elements/ElButton.vue')['default']
    ElCheckbox: typeof import('./src/components/elements/ElCheckbox.vue')['default']
    ElDatePicker: typeof import('./src/components/elements/ElDatePicker.vue')['default']
    ElInputOtp: typeof import('./src/components/elements/ElInputOtp.vue')['default']
    ElInputText: typeof import('./src/components/elements/ElInputText.vue')['default']
    ElLayer: typeof import('./src/components/elements/ElLayer.vue')['default']
    ElPassword: typeof import('./src/components/elements/ElPassword.vue')['default']
    ElRadioButton: typeof import('./src/components/elements/ElRadioButton.vue')['default']
    ElRating: typeof import('./src/components/elements/ElRating.vue')['default']
    ElTextarea: typeof import('./src/components/elements/ElTextarea.vue')['default']
    ElToggleSwicth: typeof import('./src/components/elements/ElToggleSwicth.vue')['default']
    ElToggleSwitch: typeof import('./src/components/elements/ElToggleSwitch.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LnbLayout: typeof import('./src/components/layout/LnbLayout.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    TestElement: typeof import('./src/components/layout/test-element.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('./src/components/layout/Toolbar.vue')['default']
  }
}
