/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AppToolbar: typeof import('./src/components/layout/AppToolbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ClAccordion: typeof import('./src/components/layout/control/ClAccordion.vue')['default']
    ClColumns: typeof import('./src/components/layout/control/ClColumns.vue')['default']
    ColorPicker: typeof import('primevue/colorpicker')['default']
    ComponentPalette: typeof import('./src/components/layout/ComponentPalette.vue')['default']
    ControlAccordionLayout: typeof import('./src/components/layout/control/ControlAccordionLayout.vue')['default']
    ControlColumnsLayout: typeof import('./src/components/layout/control/ControlColumnsLayout.vue')['default']
    ControlLayout: typeof import('./src/components/layout/ControlLayout.vue')['default']
    ControlRowsLayout: typeof import('./src/components/layout/ControlRowsLayout.vue')['default']
    copy: typeof import('./src/components/elements/ElAccordion copy.vue')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    Drawer: typeof import('primevue/drawer')['default']
    DrawerDialog: typeof import('./src/components/typeSelct/DrawerDialog.vue')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    ElAccordion: typeof import('./src/components/elements/ElAccordion.vue')['default']
    ElButton: typeof import('./src/components/elements/ElButton.vue')['default']
    ElCheckbox: typeof import('./src/components/elements/ElCheckbox.vue')['default']
    ElDataTable: typeof import('./src/components/elements/ElDataTable.vue')['default']
    ElDatePicker: typeof import('./src/components/elements/ElDatePicker.vue')['default']
    ElDivider: typeof import('./src/components/elements/ElDivider.vue')['default']
    ElInputOtp: typeof import('./src/components/elements/ElInputOtp.vue')['default']
    ElInputText: typeof import('./src/components/elements/ElInputText.vue')['default']
    ElLayer: typeof import('./src/components/elements/ElLayer.vue')['default']
    ElPaginator: typeof import('./src/components/elements/ElPaginator.vue')['default']
    ElPanel: typeof import('./src/components/elements/ElPanel.vue')['default']
    ElPassword: typeof import('./src/components/elements/ElPassword.vue')['default']
    ElRadioButton: typeof import('./src/components/elements/ElRadioButton.vue')['default']
    ElRating: typeof import('./src/components/elements/ElRating.vue')['default']
    ElTabs: typeof import('./src/components/elements/ElTabs.vue')['default']
    ElTextarea: typeof import('./src/components/elements/ElTextarea.vue')['default']
    ElToggleSwicth: typeof import('./src/components/elements/ElToggleSwicth.vue')['default']
    ElToggleSwitch: typeof import('./src/components/elements/ElToggleSwitch.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    InputGroup: typeof import('primevue/inputgroup')['default']
    InputGroupAddon: typeof import('primevue/inputgroupaddon')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    InputOtp: typeof import('primevue/inputotp')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LnbLayout: typeof import('./src/components/layout/LnbLayout.vue')['default']
    MainLayout: typeof import('./src/components/layout/MainLayout.vue')['default']
    Message: typeof import('primevue/message')['default']
    Panel: typeof import('primevue/panel')['default']
    Password: typeof import('primevue/password')['default']
    Popover: typeof import('primevue/popover')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    Rating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    TestElement: typeof import('./src/components/layout/test-element.vue')['default']
    Textarea: typeof import('primevue/textarea')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Toolbar: typeof import('./src/components/layout/Toolbar.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
